language: node_js
node_js:
 - "11.6.0"

install:
  - npm install -g serverless
  - npm install -g mocha

deploy:
  - provider: script
    script: sls deploy
    skip_cleanup: true
    on:
      branch: master