language: node_js
node_js:
 - "node"

install:
  - npm install -g serverless
  - npm install -g serverless-cloudflare-workers

deploy:
  - provider: script
    script: sls deploy
    skip_cleanup: true
    on:
      branch: master