service:
    name: hello-world

provider:
  name: cloudflare
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}

plugins:
  - serverless-cloudflare-workers

functions:
  hello:
    name: serverless-money
    script: worker
    events:
      - http:
          url: travis-flats.tombrightbill.com/*

